### ISSUE TITLE
Using enviroment variable as write key gives error

### ISSUE THREAD

**Issue by georgiai1** [dansmaculotte/nuxt-segment#11]
When I use the following code
`    [
      "@dansmaculotte/nuxt-segment",
      {
        writeKey: process.env.SEGMENT_ID,
        disabled: false,
        useRouter: true
      }
    ]
`

I get `Please enter a Segment Write Key`
And if I enter the string directly it works without problem but I want to use different keys for staging and production

**Comment by gaelreyrol** [comment]
Hi @gkkirilov,

How do you define the variable `SEGMENT_ID` ?
Did you configured dotenv package in your `nuxt.config.js` file ?

**Comment by georgiai1** [comment]
Hey, thanks for the fast reply,

As I am deploying this on GCP I don't have full control over it, but on localhost this is working.

I have defined the SEGMENT_ID in the env variables, but think this is a bug with Nuxt and GCP.

Anyway, I will report that in the main repo.

Thanks for the reply

**Comment by georgiai1** [comment]
Maybe I will add a pull request for [runtime config](https://nuxtjs.org/blog/moving-from-nuxtjs-dotenv-to-runtime-config/#what-are-environment-variables) in the future if I don't find another solution.

[reference](https://github.com/nuxt-community/gtm-module/commit/2bc173538ea255deea13ad575fefc82b7a28e3f0)

**Comment by gaelreyrol** [comment]
Okay, let me know if you need any help here.
