### ISSUE TITLE
When do you publish the new version ?

### ISSUE THREAD

**Issue by LouisMazel** [dansmaculotte/nuxt-segment#40]
Hi, 

Do you know when you will release the new version on npm with nuxt `runtimeConfig` support?

Thanks !

**Comment by kwolniak** [comment]
i think it is already published, see `publicRuntimeConfig` in README file

**Comment by LouisMazel** [comment]
@kwolniak When I published the issue (12 days ago), the branch was merged but the library had not been updated

The library was updated 11 days ago :

![image](https://user-images.githubusercontent.com/12446546/157089120-48da3f47-eb70-489a-9c26-a813f06fddee.png)

Thanks.

**Comment by kwolniak** [comment]
@LouisMazel anyway, i added today two more issues

**Comment by rtouze** [comment]
Yes I published your patch, I forgot to notice, sorry.
